const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Database = require('better-sqlite3');
const { normalizeDisplayText, fallbackDisplayName, loadDisplayNameMap } = require('../lib/catalogDisplayNames');
const { enrich, parsePageTitle, chooseCandidate, invariantDigest, readPageHeader, recoverSearchPages, nameKeys } = require('./enrichDisplayNames');

async function main() {
  assert.equal(normalizeDisplayText('  Beyonc&eacute; &amp;amp; Jay\u00a0Z  '), 'Beyoncé & Jay Z');
  assert.equal(normalizeDisplayText('Rock &#x26; Roll &#39;90s'), "Rock & Roll '90s");
  assert.equal(normalizeDisplayText('AC/DC\nLive\u0000'), 'AC/DC Live');
  assert.equal(fallbackDisplayName('the-proclaimers'), 'The Proclaimers');
  assert.equal(fallbackDisplayName('500_miles'), '500 Miles');
  assert.equal(fallbackDisplayName("Don't Stop (Live)!"), "Don't Stop (Live)!");
  assert.equal(fallbackDisplayName('AC/DC'), 'AC/DC');
  assert.equal(fallbackDisplayName('the-world-without-logos-(hellsing-opening)'), 'The World Without Logos (Hellsing Opening)');
  const song = { artist_slug: 'the-proclaimers', title_slug: '500-miles' };
  assert.deepEqual(parsePageTitle('500 Miles by The Proclaimers Chords, Melody, and Music Theory Analysis - Hooktheory', song), { title: '500 Miles', artist: 'The Proclaimers' });
  assert.equal(parsePageTitle('Wrong by Other Artist Chords, Melody, and Music Theory Analysis - Hooktheory', song), null);
  assert.equal(parsePageTitle('Different Song by The Proclaimers Chords, Melody, and Music Theory Analysis - Hooktheory', song), null);
  assert.equal(parsePageTitle('500 Miles by The Proclaimers', song), null);
  assert.equal(chooseCandidate([{ value: 'AB', source: 'one', priority: 1 }, { value: 'Ab', source: 'two', priority: 1 }], 'ab').source, 'conflict');
  assert(nameKeys('AC/DC').includes('ac-slash-dc'));
  assert(nameKeys('10/10').includes('10-slash-10'));
  assert(nameKeys('A&W').includes('a-and-w'));

  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'acquiring-display-names-'));
  const pagesDir = path.join(root, 'paging', 'search-pages');
  fs.mkdirSync(pagesDir, { recursive: true });
  const hits = Array.from({ length: 1000 }, (_, id) => ({ id, artist: 'Fixture', song: 'Song ' + id }));
  for (const offset of [0, 1000]) fs.writeFileSync(path.join(pagesDir, `page-${String(offset).padStart(7, '0')}.json`), JSON.stringify({ offset, hits }));
  let consumed = 0;
  const repeatedPage = await recoverSearchPages({ outputDir: path.dirname(pagesDir), offline: true }, () => consumed++);
  assert.equal(repeatedPage.status, 'repeated-page');
  assert.equal(consumed, 1);
  fs.writeFileSync(path.join(pagesDir, 'page-0000000.json'), JSON.stringify({ offset: 0, hits: [], total: 20 }));
  const truncated = await recoverSearchPages({ outputDir: path.dirname(pagesDir), offline: true }, () => {});
  assert.equal(truncated.complete, false);
  assert.equal(truncated.status, 'pagination-incomplete');
  const sourceDb = path.join(root, 'source.db');
  const catalog = path.join(root, 'input.db');
  const harvestRoot = path.join(root, 'harvest');
  const outputDir = path.join(root, 'staged');
  const slug = 'the-proclaimers__500-miles';
  const url = 'https://www.hooktheory.com/theorytab/view/the-proclaimers/500-miles';
  const source = new Database(sourceDb);
  source.exec('CREATE TABLE songs (slug TEXT PRIMARY KEY,artist_slug TEXT,title_slug TEXT,artist TEXT,title TEXT,url TEXT); CREATE TABLE song_details (slug TEXT PRIMARY KEY,hooktheory_song_name TEXT)');
  source.prepare('INSERT INTO songs VALUES (?,?,?,?,?,?)').run(slug, 'the-proclaimers', '500-miles', 'the proclaimers', '500 miles', url);
  source.prepare('INSERT INTO song_details VALUES (?,?)').run(slug, '500 Miles');
  source.close();
  const input = new Database(catalog);
  input.exec(fs.readFileSync(path.resolve(__dirname, '../../../../contracts/catalog/schema.sql'), 'utf8'));
  input.prepare('INSERT INTO songs VALUES (?,?,?,?,?,?)').run(slug, 'the-proclaimers', '500 Miles', url, 'enriched', Buffer.from('unchanged musical payload'));
  input.prepare('INSERT INTO song_browse_entries VALUES (?,?,?,?,?,?)').run(slug, 'the-proclaimers', '500 Miles', '5', 50, '50-59');
  input.prepare('INSERT INTO song_browse_modes VALUES (?,?)').run(slug, 'major');
  input.prepare('INSERT INTO songs VALUES (?,?,?,?,?,?)').run('the-proclaimers__other-song', 'the-proclaimers', 'Other Song', 'https://www.hooktheory.com/theorytab/view/the-proclaimers/other-song', 'enriched', Buffer.from('older exported payload'));
  input.prepare('INSERT INTO song_browse_entries VALUES (?,?,?,?,?,?)').run('the-proclaimers__other-song', 'the-proclaimers', 'Other Song', 'O', 30, '30-39');
  const digest = invariantDigest(input);
  input.close();
  const folder = path.join(harvestRoot, slug);
  fs.mkdirSync(folder, { recursive: true });
  fs.writeFileSync(path.join(folder, 'scrape.json'), JSON.stringify({ url, title: '500 Miles by The Proclaimers Chords, Melody, and Music Theory Analysis - Hooktheory', payload: 'x'.repeat(100000) }));
  assert.equal(readPageHeader(path.join(folder, 'scrape.json')).url, url);
  const report = await enrich({ sourceDb, catalog, harvestRoot, outputDir, offline: true });
  assert.equal(report.counts.bothRecovered, 2);
  assert.equal(report.counts.existingExportOnlySongs, 1);
  assert.equal(report.network.status, 'offline');
  assert.equal(report.staged.preservedDataSHA256, digest);
  assert.equal(loadDisplayNameMap(path.join(outputDir, 'names.json')).get(slug).artist, 'The Proclaimers');
  const staged = new Database(path.join(outputDir, 'catalog.db'), { readonly: true });
  assert.equal(staged.prepare('SELECT artist FROM songs').get().artist, 'The Proclaimers');
  assert.equal(staged.prepare('SELECT alphaGroup FROM song_browse_entries').get().alphaGroup, '5');
  assert.equal(invariantDigest(staged), digest);
  assert.equal(staged.prepare('SELECT COUNT(*) AS n FROM songs').get().n, 2);
  staged.close();
  const original = new Database(catalog, { readonly: true });
  assert.equal(original.prepare('SELECT artist FROM songs').get().artist, 'the-proclaimers');
  assert.equal(invariantDigest(original), digest);
  original.close();
  const repeated = await enrich({ sourceDb, catalog, harvestRoot, outputDir, offline: true, resume: true });
  assert.deepEqual(repeated.counts, report.counts);
  assert.equal(repeated.staged.preservedDataSHA256, digest);
  await assert.rejects(enrich({ sourceDb, catalog, harvestRoot, outputDir, offline: true }), /already initialized/);
  console.log('displayNameEnrichmentTest: passed (formatting, matching, staging, invariants, resume, original preservation)');
}

main().catch(error => { console.error(error); process.exitCode = 1; });
